import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import localFont from "next/font/local";
import { useEffect, useState } from "react";
import TopLabel from "./components/top-label";
import Script from "next/script";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script id="show-banner">
        {` var _lg_form_init_ = {
      aid: "13405",
      template: "elvis-us",
    }`}
      </Script>
      <Script
        type="text/javascript"
        async={true}
        src="https://loansaccount.com/form/applicationInit.js"
      ></Script>
      <body className="">
        <TopLabel />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
